# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
bottle:
  info:
    bno: 1
    companyName: Milton
    color: [pink , red , white]
    capacity:
    - 1
    - 3
    - 4
    types:
    - 1
    - 2
    - 2
    bottleDtail:
      height: 10
    bottleDetail:
      width: 20
    detail:
      material: plastic
      durabality: high
      strength: high
